name: CI

env:
  GO_VERSION: 1.24.6

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          ./govulncheck.sh
          ./staticcheck.sh
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: $GO_VERSION
      - run: go test -v ./...

  build:
    needs:
      - test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: $GO_VERSION
      - run: go build -v ./...

      - name: Run Linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run --skip-files '.*_test\.go$'