name: CI Pipeline

env:
  GO_VERSION: 1.24.6

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    name: Code Analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run govulncheck
        run: ./scripts/govulncheck.sh

      - name: Run staticcheck
        run: ./scripts/staticcheck.sh

  test:
    name: Run Tests
    needs: analyze
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Tests
        run: |
          ./scripts/launch-tests.sh

  build:
    name: Build
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: |
          cd ./src
          go build -v -o .././bin/app ./cmd/server